# Generated by Django 3.0.6 on 2020-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do aparelho')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('potencia', models.IntegerField(blank=True, null=True, verbose_name='Potencia em watts')),
                ('tempo', models.IntegerField(blank=True, null=True, verbose_name='Tempo sugerido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'db_table': 'aparelho',
            },
        ),
    ]
