# Generated by Django 3.0.6 on 2020-06-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aparelho',
            options={'ordering': ['name'], 'verbose_name': 'aparelho', 'verbose_name_plural': 'Aparelho'},
        ),
    ]
